### PR TITLE
Find layout

### PR DESCRIPTION
**Pull request by JustinHsie**
Created the find layout

### CODE REVIEW

**Comment by Exegetech** [comment]
In general when we work in a branch, we want to fork off master, not the previous unmerged branch, unless you know that the files that you will touch in the new branch is totally different than the files in the previous unmerged branch. Yeah this is harder in the previous early commits in the app because no structure is set in place yet.

The reason is because previous unmerged branch might require fixes (i.e, I might reject your PR or require you to fix the PR first before merging), thus changing the git history, and then later when you want to merge it you will have merge conflicts. This is fine, it is just later you need to fix the merge conflicts.

Another reason is because these commits that you are having in this PR is already addressed in another PR, thus confusing the PR reviewers.

**Comment by JustinHsie** [comment]
Ok that makes sense, thanks so much! I thought about it for a while but decided to keep the previous additions to work off of. Bad idea lol. The most recent site is on heroku though bc I could push the full version there

So would it be a good idea to reject these PRs and I can try merging them locally into one branch? Then I can make a new single PR so it's easier for you to point out what I should fix? Sorry it's a mess

**Comment by Exegetech** [comment]
> Ok that makes sense, thanks so much! I thought about it for a while but decided to keep the previous additions to work off of. Bad idea lol. The most recent site is on heroku though bc I could push the full version there
> 
> So would it be a good idea to reject these PRs and I can try merging them locally into one branch? Then I can make a new single PR so it's easier for you to point out what I should fix? Sorry it's a mess

Yes, so what needs to be done in order:
1. I will merge the previous PR once you address the changes
2. I will reject these two PRs
3. Now the master should be updated, update your local master
4. Fork off your local master to a new branch, lets call it find-layout-2 for example, don't delete find-layout yet
5. Cherry-pick the commit one by one in order, and apply it one by one to find-layout-2 branch, and cleanup the merge conflict (google git cherry-pick for more details). Once you apply the cherry-picked commit then you can delete find-layout
6. Git push find-layout-2
7. Make a PR.

Or if you don't want to do cherry-pick (step 5), just manually code the feature again

**Comment by Exegetech** [comment]
For heroku, create 1 more app, name it eats-dev so the URL will be like eats-dev.herokuapp.com instead of eats.herokuapp.com

You can push your branches that are work in progress to eats-dev so I can see it.

Generally teams have 3 target build. the dev, staging and the main one. Dev is for development, with fake data, staging is for QA people to find bugs, also with fake data, and the main one is the production one, with real user data.

We don't need staging for now, just dev and main.

**Comment by Exegetech** [comment]
One PR should be for one feature/bug/issue ideally. This allows for more critical eye to see the PR, high signal to noise ratio.

**Comment by JustinHsie** [comment]
Ok I finished cherry-picking and made a PR!

I also made the heroku dev app, I'll add it to the wiki

**Pull request closed without merging**
